#!/bin/bash
# check for homebrew
if test "$(uname)" = "Darwin"; then
  if test ! "$(which brew)"; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  brew install ansible
elif test "$(uname)" = "Linux"; then
  if test "$(which yum)"; then
    sudo yum install ansible
  elif test "$(which apt)"; then
    sudo apt-get install software-properties-common
    sudo apt-add-repository ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install -y ansible
  fi
fi

ansible-galaxy install -r requirements.yml -p roles
ansible-playbook -i hosts --ask-sudo-pass main.yml
