#!/bin/bash
set -x
if test "$(uname)" = "Darwin"; then
  if test ! $(which gcc); then
    echo "Installing xcode..."
    xcode-select --install
  fi
  if test ! "$(which brew)"; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  echo "Installing ansible..."
  brew update
  brew install ansible
elif test "$(uname)" = "Linux"; then
  if test -f /etc/lsb-release; then
    echo "Installing ansible..."
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install -y ansible
  fi
  cat <<EOF >> ./ansible.cfg

[privilege_escalation]
become = True
EOF
fi

if test ! "$(which ansible)"; then
  echo "Not supported yet."
  exit 1
fi

python --version
ansible-playbook main.yml
