- name: Install PostgresApp
  homebrew_cask: name=postgres
  when: is_osx

- name: Install PostgreSQL
  package: name={{ item }}
  with_items:
    - postgresql
    - postgresql-contrib
  when: is_ubuntu
- name: Setup pg_hba
  copy: src=pg_hba.conf dest={{ lookup('pipe', 'ls /etc/postgresql/9.*/main/pg_hba.conf') }} mode=0750
  when: is_ubuntu
- name: Setup postgresql.conf
  lineinfile: dest={{ lookup('pipe', 'ls /etc/postgresql/9.*/main/postgresql.conf') }} line="listen_addresses = '*'"
  when: is_ubuntu
- name: Install pg_activity
  pip: name=pg_activity
  ignore_errors: yes
